stages:
    - build

build:
  stage: build
  only:
    - master
  script:
#    - docker login -u %DOCKERIO_USER% -p %DOCKERIO_PASSWORD%
    - docker build -t chemsorly/msbuilder:latest -f .\dockerfiles\msbuild.Dockerfile .
    - docker push chemsorly/msbuilder:latest
    
build-vsc:
  stage: build
  only:
    - master
  script:
#    - docker login -u %DOCKERIO_USER% -p %DOCKERIO_PASSWORD%
    - docker build -t chemsorly/msbuilder:latest-vsc -f .\dockerfiles\msbuild-vsc.Dockerfile .
    - docker push chemsorly/msbuilder:latest-vsc

after_script:
    - powershell docker rmi $(docker images -aq) -f