variables:
    ASSETCONTAINER_NAME: "msbuilder-assets-$CI_BUILD_REF"

stages:
    - build

build:
  stage: build
  only:
    - master
  script:
    - docker build -t chemsorly/msbuilder:latest -t chemsorly/msbuilder:%PROJECT_VERSION% -f .\dockerfiles\msbuild.Dockerfile .
    - docker push chemsorly/msbuilder:latest
    - docker push chemsorly/msbuilder:%PROJECT_VERSION%
    
build-vsc:
  stage: build
  only:
    - master
  script:
    - docker build -t chemsorly/msbuilder:latest-vsc -t chemsorly/msbuilder:%PROJECT_VERSION%-vsc -f .\dockerfiles\msbuild-vsc.Dockerfile .
    - docker push chemsorly/msbuilder:latest-vsc
    - docker push chemsorly/msbuilder:%PROJECT_VERSION%-vsc

after_script:
    - docker rm %ASSETCONTAINER_NAME% -f
    - powershell docker rmi $(docker images -aq) -f